# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0



source "https://rubygems.org"

gem "net-smtp", "~> 0.5.1"
gem "pony",     "~> 1.13"
gem "puma",     "~> 8.0"
gem "sinatra",  "~> 4.2"
gem "rackup",   "~> 2.3"

gem "google-protobuf", "~> 4.35.1"

gem "ostruct"

# Application source depends only on the OpenTelemetry API. The SDK, exporters
# and auto-instrumentation are declared in ./otel/Gemfile and injected at the
# container layer (see src/email/otel_bootstrap.rb + RUBYOPT in the Dockerfile).
gem "opentelemetry-api", "~> 1.5"

gem "openfeature-sdk", "~> 0.6"
gem "openfeature-flagd-provider", "~> 0.1"
